version: '3.8'

x-external: true
services:
  bedrock:
    # image: itzg/minecraft-bedrock-server:2024.11.0
    image: harbor.server.unarmedpuppy.com/docker-hub/itzg/minecraft-bedrock-server:2024.11.0
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      OPS: "2535454866260420"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
    labels:
      - "homepage.group=Gaming"
      - "homepage.name=Minecraft Bedrock Server"
      - "homepage.icon=si-modrinth"
      - "homepage.href=http://minecraft.server.unarmedpuppy.com"
      - "homepage.description=Minecraft server, UDP traffic only on port 19132"
    networks:
      - my-network

networks:
  my-network:
    external: true
