services:
  vaultwarden:
    image: vaultwarden/server:1.32.2
    container_name: vaultwarden
    restart: always
    environment:
      - DOMAIN=https://vaultwarden.server.unarmedpuppy.com  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      - SIGNUPS_ALLOWED=false # Deactivate this with "false" after you have created your account so that no strangers can register
      # - SMTP_HOST=smtp.gmail.com
      # - SMTP_FROM=dangerbahn@gmail.com
      # - SMTP_PORT=587
      # - SMTP_SECURITY=force_tls
      # - SMTP_USERNAME=dangerbahn@gmail.com
      # - SMTP_PASSWORD=${SMTPPASS}
      # - SMTP_AUTH_MECHANISM=Plain
    volumes:
      - vaultwarden:/data
    ports:
      - 11001:80 # you can replace the 11001 with your preferred port
    networks:
      - my-network
    labels:
      - "traefik.enable=true"
      # HTTPS redirect
      - traefik.http.middlewares.mywebserver-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.vaultwarden-redirect.middlewares=mywebserver-redirect-web-secure
      - traefik.http.routers.vaultwarden-redirect.rule=Host(`vaultwarden.server.unarmedpuppy.com`)
      - traefik.http.routers.vaultwarden-redirect.entrypoints=web
      # Main HTTPS router
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.server.unarmedpuppy.com`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure" # your https endpoint
      - "traefik.http.routers.vaultwarden.tls.certresolver=myresolver" # your cert resolver
      - "homepage.group=Apps"
      - "homepage.name=Vaultwarden"
      - "homepage.icon=si-1password"
      - "homepage.description=passwords"
      - "homepage.href=https://vaultwarden.server.unarmedpuppy.com"

volumes:
  vaultwarden:

networks:
  my-network:
    external: true