services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      # DOMAIN: "https://vaultwarden.example.com"  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "true" # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - vaultwarden:/data
    ports:
      - 11001:80 # you can replace the 11001 with your preferred port
    labels:
      - "homepage.group=Apps"
      - "homepage.name=Vaultwarden"
      - "homepage.icon=si-1password"
      - "homepage.description=passwords"
      - "homepage.href=http://192.168.86.47:11001"

volumes:
  vaultwarden: