version: '3.5'
services:
  jellyfin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - jellyfinconf:/config
      - jellyfincache:/cache
      - type: bind
        source: ${ZFS_PATH}
        target: /media
    restart: 'unless-stopped'
volumes:
  jellyfinconf:
  jellyfincache: