version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: "${UID}:${GID}"
    command: ["/bin/bash", "entrypoint.sh"]
    container_name: jellyfin
    volumes:
      - jellyfinconf:/config
      - jellyfincache:/cache
      - type: bind
        source: ${ZFS_PATH}
        target: /media
      - type: bind
        source: /jenquist-cloud
        target: /jenquist-cloud
    ports:
      - "8096:8096"
    restart: 'unless-stopped'
    networks:
      - my-network
    labels:
      - "homepage.group=Services"
      - "homepage.name=Cache"
      - "homepage.icon=si-redhat"
      - "homepage.href=https://http://192.168.86.47:8096"
      - "homepage.description=Manage cache and resources"
volumes:
  jellyfinconf:
  jellyfincache:

networks:
  my-network:
    external: true