version: '3.5'

# Auto-start configuration: disabled because it requires manual ZFS unlock
x-enabled: false

services:
  jellyfin:
    image: jellyfin/jellyfin
    user: "${UID}:${GID}"
    command: ["/bin/bash", "entrypoint.sh"]
    container_name: jellyfin
    environment:
      - ZFS_PATH=${ZFS_PATH}
    volumes:
      - jellyfinconf:/config
      - jellyfincache:/cache
      - type: bind
        source: ${ZFS_PATH}
        target: /media
      - type: bind
        source: /jenquist-cloud
        target: /jenquist-cloud
    ports:
      - "8169:8096"
    restart: 'no'
    networks:
      - my-network
    labels:
      - "homepage.group=Media & Entertainment"
      - "homepage.name=Cache"
      - "homepage.icon=si-jellyfin"
      - "homepage.href=http://192.168.86.47:8169"
      - "homepage.description=Manage cache and resources"
volumes:
  jellyfinconf:
  jellyfincache:

networks:
  my-network:
    external: true