version: '3.5'
services:
  jellyfin:
    user: "${UID}:${GID}"
    command: ["/bin/bash", "./entrypoint.sh"]
    container_name: jellyfin
    volumes:
      - jellyfinconf:/config
      - jellyfincache:/cache
      - type: bind
        source: ${ZFS_PATH}
        target: /media
    restart: 'unless-stopped'
    networks:
      - my-network

volumes:
  jellyfinconf:
  jellyfincache:

networks:
  my-network:
    external: true