version: "3"

services:
  adguard:
    container_name: adguard
    hostname: adguard
    image: adguard/adguardhome:latest
    ports:
      # 3003:3000/tcp # only required during initial setup
      - 8083:80/tcp # web interface after setup
      - 53:53/tcp # dns
      - 53:53/udp # dns
      # - 67:67/udp # dhcp
      # - 68:68/tcp # dhcp
      # - 68:68/udp # dhcp
      # - 784:784/udp # dns-over-quic
      # - 853:853/tcp # dns over tls
      # - 853:853/udp # dns over tls
      # - 5443:5443/tcp # dnscrypt
      # - 5443:5443/udp # dnscrypt
    restart: unless-stopped
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    networks:
      - my-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.server.unarmedpuppy.com`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=8083"
      - "traefik.http.routers.adguard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=unarmedpuppy:$$apr1$$yE.A6vVX$$p7.fpGKw5Unp0UW6H/2c.0"
      - "traefik.http.routers.adguard.entrypoints=web"
      #- "traefik.http.routers.adguard.tls.certresolver=myresolver"
      - "homepage.group=Services"
      - "homepage.name=Adguard"
      - "homepage.icon=/icons/icon.png"
      - "homepage.href=https://adguard.server.unarmedpuppy.com"
      - "homepage.description=Adguard Home instance"

networks:
  my-network:
    external: true
