version: '3.1'

services:
  tailscale:
    image: tailscale/tailscale:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscale-volume:/var/lib/tailscale
    command: ["tailscaled"]
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=tskey-auth-kq8ZZz6CNTRL-ySrwZtner83AryykCZxJ93xgnNVne8Vf
    labels:
      - "homepage.group=Services"
      - "homepage.name=Tailscale"
      - "homepage.icon=si-wireguard"
      - "homepage.description=VPN"

volumes:
  tailscale-volume:
