version: '3.1'

services:
  tailscale:
    image: tailscale/tailscale:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscale-volume:/var/lib/tailscale
    command: ["tailscaled"]
    environment:
      - TS_AUTHKEY=tskey-auth-kq8ZZz6CNTRL-ySrwZtner83AryykCZxJ93xgnNVne8Vf

volumes:
<<<<<<< HEAD
  tailscale-volume: 
=======
  tailscale-volume:
>>>>>>> 160364332635faff837e41f5f39ec49fbb20caab
