version: '3'

services:
  bedrock-viz-http:
    image: nginx
    container_name: bedrock-viz-http
    ports:
      - 8081:80
    volumes:
      - ~/server/apps/bedrock-viz/data/repo/build/output:/usr/share/nginx/html:ro
    labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.bedrock-viz-http.rule=Host(`minecraft.server.unarmedpuppy.com`)"
      #- "traefik.http.routers.bedrock-viz-http.entrypoints=web"
      #- "traefik.http.services.bedrock-viz-http.loadbalancer.server.port=80"
      - "homepage.group=Apps"
      - "homepage.name=Bedrock Viz"
      - "homepage.icon=si-maplibre"
      - "homepage.href=http://192.168.86.47:8081"
      - "homepage.description=Visualization of Minecraft Server map"
    networks:
      - my-network

networks:
  my-network:
    external: true
