version: '3'

services:
  bedrock-viz-http:
    image: nginx
    container_name: bedrock-viz-http
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ~/server/apps/bedrock-viz/data/output:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      # HTTPS redirect
      - traefik.http.middlewares.mywebserver-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.gumberlund-redirect.middlewares=mywebserver-redirect-web-secure
      - traefik.http.routers.gumberlund-redirect.rule=Host(`gumberlund.server.unarmedpuppy.com`)
      - traefik.http.routers.gumberlund-redirect.entrypoints=web
      # Main HTTPS router
      - "traefik.http.routers.gumberlund.rule=Host(`gumberlund.server.unarmedpuppy.com`)"
      - "traefik.http.routers.gumberlund.entrypoints=websecure" # your https endpoint
      - "traefik.http.routers.gumberlund.tls.certresolver=myresolver" # your cert resolver
      - "homepage.group=Gaming"
      - "homepage.name=Bedrock Viz"
      - "homepage.icon=si-maplibre"
      - "homepage.href=https://gumberlund.server.unarmedpuppy.com"
      - "homepage.description=Visualization of Minecraft Server map"
    networks:
      - my-network

networks:
  my-network:
    external: true
