version: '3.6'
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    restart: unless-stopped
    volumes:
      - ./data/seafile/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    restart: unless-stopped

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    restart: unless-stopped
    ports:
      #- "7780:80" # HTTP
      - "7443:443"  # HTTPS
    volumes:
      - ./data/seafile/data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=America/Chicago  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=seafile@jenquist.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=MySecureLoginPassword # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=true   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=seafile.server.unarmedpuppy.com # Specifies your host name if https is enabled.
    labels:
      - traefik.enable=true

      #- traefik.http.middlewares.mywebserver-redirect-web-secure.redirectscheme.scheme=https
      #- traefik.http.routers.seafile.middlewares=mywebserver-redirect-web-secure
      #- traefik.http.routers.seafile.rule=Host(`seafile.server.unarmedpuppy.com`)
      #- traefik.http.routers.seafile.entrypoints=web

      - traefik.http.routers.seafile-secure.rule=Host(`seafile.server.unarmedpuppy.com`)
      - traefik.http.routers.seafile-secure.tls.certresolver=myresolver
      - traefik.http.routers.seafile-secure.tls=true
      - traefik.http.routers.seafile-secure.entrypoints=websecure
      - traefik.http.services.seafile-secure.loadbalancer.server.port=7443

    depends_on:
      - db
      - memcached