version: '3.8'
services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 8009:8080 # Obsidian Web Interface
      #- 27123:27123 # Local REST API Plugin HTTP Server Port
      #- 27124:27124 # Local REST API Plugin HTTPS Server Port
    volumes:
      - obsidian:/vaults # The location on the host for your Obsidian Vaults
      - obsidian:/config # The location to store Obsidan configuration and ssh data for obsidian-git
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/mods:universal-git # Use to add mods to the container like git.
      - KEYBOARD=en-us-qwerty # Used to se the keyboard being used for input. E.g. KEYBOARD=en-us-qwerty or KEYBOARD=de-de-qwertz
    labels:
      - "homepage.group=Services"
      - "homepage.name=Obsidian"
      - "homepage.icon=/icons/icon.png"
      - "homepage.href=http://obsidian.server.unarmedpuppy.com"
      - "homepage.description=Obsidian"
volumes:
  obsidian: