version: '3'
services:
  stable-diffusion:
    image: stable-diffusion:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - stablediffusion:/data
    ports:
      - 8006:8080
    command: python3 run.py

volumes:
  stablediffusion: