---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Utility:
    - Gmail:
        - abbr: GM
          href: https://mail.google.com/mail/u/0/#inbox
          icon: si-gmail
    - Github:
        - abbr: GH
          href: https://github.com/unarmedpuppy
          icon: si-github
    - WZranked:
        - abbr: WZ
          href: https://wzranked.com/wz2/meta
          icon: si-mcafee
    - Shipping Labels: 
        - abbr: SL
          href: https://www.paypal.com/signin?returnUri=https%3A%2F%2Fwww.paypal.com%2Fshiplabel%2Fcreate%2F
          icon: si-paypal

- AI Tools:
    - ChatGPT:
        - abbr: GP
          href: https://chat.openai.com/
          icon: si-openai
    - Claude:
        - abbr: CL
          href: https://claude.ai/chat
          icon: si-anthropic
    - Suno:
        - abbr: SU
          href: https://app.suno.ai/create/
          icon: si-neteasecloudmusic
    - Midjourney:
        - abbr: MI
          href: https://midjourney.com/home
          icon: si-immer

- Docs:
    - "Financial Planning":
        - abbr: FP
          href: "https://docs.google.com/spreadsheets/d/1A_-Npqi3ySqCCo7laftVPe6KR82eKKkT07XSdF2SgOs"
          icon: si-fi
    - "Trade Log":
        - abbr: LG
          href: "https://docs.google.com/spreadsheets/d/1OtUK3h5AU5BbuSRWzH88Mc7wUx0xYFlONrBzo32nGQ8/edit?gid=2073933159#gid=2073933159"
          icon: si-talenthouse
    - "Hobby Finance":
        - abbr: HF
          href: "https://docs.google.com/spreadsheets/d/1_jzIuvvti7Oh7N9frw9rFa04OvkpSURW2NWMv5iAiD8"
          icon: si-honey
    - "FIRE notes":
        - abbr: FN
          href: "https://docs.google.com/document/d/1-7RTeNd1_w6WRK_4vquTFGjK2-lD_Ta0_fnDVmKruRc"
          icon: si-fireship

- Finance:
    - "Robinhood":
        - abbr: RH
          href: "https://robinhood.com"
          icon: si-socialblade
    - "Fidelity":
        - abbr: FI
          href: "https://digital.fidelity.com/ftgw/digital/portfolio/summary"
          icon: si-socialblade
    - "Vanguard":
        - abbr: VA
          href: "https://logon.vanguard.com/logon"
          icon: si-vectorlogozone
    - "BCU":
        - abbr: BU
          href: "https://bcu.org/"
          icon: si-bricks
  
- Trading:
    - "Journal":
        - abbr: JR
          href: "https://www.tradesviz.com/home/"
          icon: si-journal
    - "Option Strat":
        - abbr: OS
          href: "https://optionstrat.com/saved"
          icon: si-openstreetmap
    - "Trading View":
        - abbr: TV
          href: "https://www.tradingview.com"
          icon: si-gamejolt
    - "Unusual Whales":
        - abbr: UNS
          href: "https://unusualwhales.com/live-options-flow/free?exclude_deep_itm=true&intraday_only=true&issue_types[]=Common%20Stock&limit=50&max_dte=35&min_premium=10000&min_size=100&newer_than=1717650000000&older_than=1719291540000&order=Prem&ticker_symbol=GME&watchlist_name=GME%2035DTE"
          icon: si-docker
    - "BTC stats":
        - abbr: BT
          href: "https://newhedge.io/terminal/bitcoin"
          icon: si-bitcoin

- MTG:
    - "Moxfield":
        - abbr: MX
          href: "https://moxfield.com/users/unarmedpuppy"
          icon: si-steamdeck
    - "Cube Cobra":
        - abbr: CC
          href: "https://cubecobra.com/cube/list/playmats-are-strong-v2"
          icon: si-nintendogamecube
    - "TCGPlayer":
        - abbr: TP
          href: "https://tcgplayer.com"
          icon: si-sketch
    - "EDHREC":
        - abbr: ER
          href: "https://edhrec.com/"
          icon: si-anydesk

- Tech:
    - "Refcards":
        - abbr: MX
          href: "https://dzone.com/refcardz"
          icon: si-steamdeck
    - "Radar":
        - abbr: CC
          href: "https://www.thoughtworks.com/radar"
          icon: si-nintendogamecube
    - "InfoQ":
        - abbr: TP
          href: "https://www.infoq.com/"
          icon: si-sketch