---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Utility:
    - ChatGPT:
        - abbr: GP
          href: https://chat.openai.com/
          icon: si-openai
    - Gmail:
        - abbr: GM
          href: https://mail.google.com/mail/u/0/#inbox
          icon: si-gmail
    - Github:
        - abbr: GH
          href: https://github.com/unarmedpuppy
          icon: si-github

- Media:
  - Reddit:
      - abbr: rd
        href: https://www.reddit.com/
        icon: si-reddit
  - Youtube:
      - abbr: YT
        href: https://youtube.com
        icon: si-youtube
  - Twitter:
      - abbr:
        href: https://twitter.com/unarmedpuppy
        icon: si-twitter

- Finance:
    - "Financial Planning":
        - abbr: FP
          href: "https://docs.google.com/spreadsheets/d/1A_-Npqi3ySqCCo7laftVPe6KR82eKKkT07XSdF2SgOs"
          icon: si-fi
    - "Hobby Finance":
        - abbr: HF
          href: "https://docs.google.com/spreadsheets/d/1_jzIuvvti7Oh7N9frw9rFa04OvkpSURW2NWMv5iAiD8"
          icon: si-honey
    - "FIRE notes":
        - abbr: FN
          href: "https://docs.google.com/document/d/1-7RTeNd1_w6WRK_4vquTFGjK2-lD_Ta0_fnDVmKruRc"
          icon: si-fireship

- MTG:
    - "Moxfield":
        - abbr: MX
          href: "https://www.moxfield.com/users/unarmedpuppy"
          icon: si-steamdeck
    - "Cube Cobra":
        - abbr: CC
          href: "https://cubecobra.com/cube/list/playmats-are-strong-v2"
          icon: si-nintendogamecube
    - "TCGPlayer":
        - abbr: TP
          href: "https://tcgplayer.com2"
          icon: si-sketch
