---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: unarmedpuppy's Home Server
background: /images/background-1.webp

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
