---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: unarmedpuppy's Home Server

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
