---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets
- resources:
    label: system
    cpu: true
    cputemp: true
    uptime: true
    memory: true

- resources:
    label: storage
    disk:
      - /
      - /mnt/server-cloud
      - /mnt/server-storage

- search:
    provider: duckduckgo
    target: _blank
