---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets
- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- openmeteo:
    label: Golden Valley
    latitude: 45.004869
    longitude: -93.343433
    timezone: America/Chicago # optional
    units: imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits

#- logo:
    #icon: https://avatars.githubusercontent.com/u/1477193?v=4

- datetime:
    text_size: sm
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
