---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets
- resources:
    cpu: true
    cputemp: true
    uptime: true
    memory: true
    expanded: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank
