version: '3'

services:
  vikunja:
    image: vikunja/vikunja
    environment:
      #VIKUNJA_SERVICE_PUBLICURL: http://<the public url where vikunja is reachable>
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: telling-headset-resile-mobster
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja-puppy
      VIKUNJA_DATABASE_DATABASE: vikunja-puppy
      VIKUNJA_SERVICE_JWTSECRET: u3kj9MrB7mdibwdQQsKb
    ports:
      - 3456:3456
    volumes:
      - vikunja:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      #local DNS
      - "traefik.http.routers.vikunja-local.rule=Host(`vikunja.local.unarmedpuppy.com`) || Host(192.168.86.47)"
      - "traefik.http.routers.vikunja-local.entrypoints=web"
      - "homepage.group=Apps"
      - "homepage.name=Vikunja"
      - "homepage.icon=si-todoist"
      - "homepage.href=http://192.168.86.47:3456/"
      - "homepage.description=Projects, To-Do lists & Kanban"
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: surreal-ginger-roughen-shipyard
      MYSQL_USER: vikunja-puppy
      MYSQL_PASSWORD: telling-headset-resile-mobster
      MYSQL_DATABASE: vikunja-puppy
    volumes:
      - vikunja-db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s

volumes:
  vikunja:
  vikunja-db: