version: '3.3'

services:
  valheim-discord-bot:
    image: ghcr.io/bearbin/discord-gamestatus:latest
    container_name: valheim-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./config:/config
    networks:
      - my-network
    labels:
      - "homepage.group=Gaming"
      - "homepage.name=Valheim Discord Bot"
      - "homepage.icon=discord"
      - "homepage.description=Server status in Discord"

networks:
  my-network:
    external: true
