version: "3.7"

services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.2.0
    container_name: mealie-frontend
    hostname: mealie-frontend
    depends_on:
      - mealie-api
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000
    restart: unless-stopped
    ports:
      - "9925:3000" # adjust to your liking 
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/mealie/data:/app/data/
    networks:
       - my-network
    labels:
      - "traefik.enable=true"
      # HTTPS redirect
      - traefik.http.middlewares.mywebserver-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.recipes-redirect.middlewares=mywebserver-redirect-web-secure
      - traefik.http.routers.recipes-redirect.rule=Host(`recipes.server.unarmedpuppy.com`)
      - traefik.http.routers.recipes-redirect.entrypoints=web
      # Main HTTPS router
      - "traefik.http.routers.recipes.rule=Host(`recipes.server.unarmedpuppy.com`)"
      - "traefik.http.routers.recipes.entrypoints=websecure" # your https endpoint
      - "traefik.http.routers.recipes.tls.certresolver=myresolver" # your cert resolver

    #  # Part for optional traefik middlewares
    #  - traefik.http.routers.mealie.middlewares=local-ipwhitelist@file,basic-auth@file      

  mealie-api:
    image: hkotel/mealie:api-v1.2.0
    container_name: mealie-api
    hostname: mealie-api
    deploy:
      resources:
        limits:
          memory: 512M # Setting a memory limit will improve idle performance.
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/mealie/data:/app/data/
    networks:
      - my-network
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true # disable after setting up your accounts!
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.example.com # adjust this!
    restart: unless-stopped

networks:
  my-network:
    external: true