version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.1.0 # 
    container_name: mealie
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://recipes.server.unarmedpuppy.com
    restart: always
    networks:
       - my-network
    labels:
      - "traefik.enable=true"
      # HTTPS redirect
      - traefik.http.middlewares.mywebserver-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.recipes-redirect.middlewares=mywebserver-redirect-web-secure
      - traefik.http.routers.recipes-redirect.rule=Host(`recipes.server.unarmedpuppy.com`)
      - traefik.http.routers.recipes-redirect.entrypoints=web
      # Main HTTPS router
      - "traefik.http.routers.recipes.rule=Host(`recipes.server.unarmedpuppy.com`)"
      - "traefik.http.routers.recipes.entrypoints=websecure" # your https endpoint
      - "traefik.http.routers.recipes.tls.certresolver=myresolver" # your cert resolver
      - "homepage.group=Services"
      - "homepage.name=Mealie - Recipes"
      - "homepage.icon=/icons/icon.png"
      - "homepage.href=https://recipes.server.unarmedpuppy.com"
      - "homepage.description=Recipes, meal planning & shopping list"

volumes:
  mealie-data:
    driver: local

networks:
  my-network:
    external: true