version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
    restart: unless-stopped
    networks:
       - my-network

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports:
      - "8042:8080"
    environment:
      - '/ollama/api=http://ollama:11434/api'
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
       - my-network
    labels:   
      - "homepage.group=Apps"
      - "homepage.name=ollama"
      - "homepage.icon=si-meta"
      - "homepage.href=http://192.168.86.47:8042"
      - "homepage.description=Ollama UI"
networks:
  my-network:
    external: false
