version: '3'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=America/Chicago
    volumes:
      - ./data/config:/config
    ports:
      - 8123:8123
    #devices:
    #  - /path/to/device:/path/to/device #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.server.unarmedpuppy.com`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=myresolver"
      #- "traefik.http.routers.homeassistant.middlewares=auth"
      #- "traefik.http.middlewares.auth.basicauth.users=unarmedpuppy:$$apr1$$yE.A6vVX$$p7.fpGKw5Unp0UW6H/2c.0"
      - "homepage.group=Apps"
      - "homepage.name=Home Assistant"
      - "homepage.icon=si-homeassistant"
      - "homepage.href=https://homeassistant.server.unarmedpuppy.com"
      - "homepage.description=Smart home & automations"
    networks:
      - my-network

networks:
  my-network:
    external: true
