version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:15-alpine
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    env_file:
      - ./data/.env
    networks:
      - default

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./data/.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./data/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - default

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - ./data/.env
    ports:
      - 8200:80
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./data/mediafiles:/media:ro
    labels:
      - "traefik.enable=true"
      # HTTPS redirect
      - traefik.http.middlewares.mywebserver-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.recipes-redirect.middlewares=mywebserver-redirect-web-secure
      - traefik.http.routers.recipes-redirect.rule=Host(`recipes.server.unarmedpuppy.com`)
      - traefik.http.routers.recipes-redirect.entrypoints=web
      # Main HTTPS router
      - "traefik.http.routers.recipes.rule=Host(`recipes.server.unarmedpuppy.com`)"
      - "traefik.http.routers.recipes.entrypoints=websecure" # your https endpoint
      - "traefik.http.routers.recipes.tls.certresolver=myresolver" # your cert resolver
      - "homepage.group=Services"
      - "homepage.name=Tandoor - Recipes"
      - "homepage.icon=/icons/icon.png"
      - "homepage.href=https://recipes.server.unarmedpuppy.com"
      - "homepage.description=Home Assistant instance"
    networks:
      - default
      - my-network

networks:
  default:
  my-network: # This is your external traefik network
    external: true

volumes:
  nginx_config:
  staticfiles:
