version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:15-alpine
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    env_file:
      - ./data/.env

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./data/.env
    volumes:
      - ./data/staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - ./data/nginx_config:/opt/recipes/nginx/conf.d
      - ./data/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 8200:80
    env_file:
      - ./data/.env
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - ./data/nginx_config:/etc/nginx/conf.d:ro
      - ./data/staticfiles:/static:ro
      - ./data/mediafiles:/media:ro
